added error handling to see what is erroring

diff --git a/.github/workflows/docker-build.yaml b/.github/workflows/docker-build.yaml
--- a/.github/workflows/docker-build.yaml
+++ b/.github/workflows/docker-build.yaml
@@ -170,13 +170,12 @@ jobs:
           echo "${{ steps.meta.outputs.tags }}" > tags.txt
           image=$(cat tags.txt)
 
-          echo $image
-
           echo "==> Tagging image with additional tags!!!"
           for i in $image; do
             image_tag=$(echo "$i" | cut -d ":" -f 2)
+            echo ${image_tag}
 
-            IMAGE_META="$( aws ecr describe-images --repository-name=${{ inputs.image_name }} --image-ids=imageTag=$image_tag 2> /dev/null )"
+            IMAGE_META="$( aws ecr describe-images --repository-name=${{ inputs.image_name }} --image-ids=imageTag=${image_tag} || (echo "Command Failed" && exit 1) )"
 
             if [[ $? != 0 ]]; then
               aws ecr put-image --repository-name ${{ inputs.image_name }} --image-tag "$image_tag" --image-manifest "$IMAGE_MANIFEST"
