Ensure files are not empty before pushing

diff --git a/.github/workflows/qa-cleanup.yaml b/.github/workflows/qa-cleanup.yaml
--- a/.github/workflows/qa-cleanup.yaml
+++ b/.github/workflows/qa-cleanup.yaml
@@ -89,14 +89,20 @@ jobs:
         run: |-
           cd ${GITHUB_WORKSPACE}/infrastructure/qa-envs
           ./qa_apps.sh remove
-          git config user.name github-actions
-          git config user.email github-actions@github.com
-          git add . && git diff --cached --quiet || \
-            git commit -m "[ci] Cleanup PR-${{ github.event.number }} from ${{ github.repository }}" && \
-            git push && \
-            git status --porcelain
-          
-          echo "QA file has been updated and pushed."
+
+          if [ -s "${QA_FILE}" -a -s "qa_lanes.libsonnet" ]; then
+            git config user.name github-actions
+            git config user.email github-actions@github.com
+            git add . && git diff --cached --quiet || \
+              git commit -m "[ci] Cleanup PR-${{ github.event.number }} from ${{ github.repository }}" && \
+              git push && \
+              git status --porcelain
+            
+            echo "QA file has been updated and pushed."
+          else
+            echo "${QA_FILE} or qa_lanes.libsonnet is empty. Aborting job."
+            exit 1
+          fi
       
       - name: Release QA Environment
         id: release-qa-env
